# Generated by Django 4.2.3 on 2023-08-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the movie', max_length=50)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('DRAMA', 'Drama'), ('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('ROMANCE', 'Romance'), ('SCI_FI', 'Sci-Fi'), ('THRILLER', 'Thriller')], max_length=20, verbose_name='Genre of the Movie')),
                ('cast', models.CharField(help_text='Cast of the movie', max_length=50)),
                ('director', models.CharField(help_text='Director of The movie', max_length=50)),
                ('runtime', models.PositiveIntegerField(help_text='Runtime of the movie in minutes')),
                ('release_date', models.DateField(verbose_name='Date of the initial release')),
                ('storyline', models.TextField(help_text='Storyline of the movie')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_time', models.DateTimeField(help_text='date and time of the screening')),
                ('seats', models.PositiveIntegerField(null=True, unique=True)),
                ('price', models.PositiveIntegerField(help_text='Price of the tickets')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField()),
                ('name', models.CharField(help_text='Name on the Ticket', max_length=20)),
                ('phone_number', models.CharField(help_text='Phone numer of the person making reservation', max_length=9, null=True)),
                ('email', models.EmailField(help_text='Email address', max_length=254, null=True)),
                ('discount', models.BooleanField(default=False)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.screening')),
            ],
        ),
    ]
