# Generated by Django 4.2.3 on 2023-08-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name on the Ticket', max_length=20)),
                ('phone_number', models.CharField(help_text='Phone numer of the person making reservation', max_length=9, null=True)),
                ('email', models.EmailField(help_text='Email address', max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='screening',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.customer'),
        ),
    ]
