# Generated by Django 4.2.3 on 2023-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_customer_remove_screening_seats_remove_ticket_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='a', help_text='Name on the Ticket', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(help_text='Phone numer of the person making reservation', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='price',
            field=models.FloatField(help_text='Price of the tickets'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
