# Generated by Django 4.2.3 on 2023-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller')], max_length=20, verbose_name='Genre of the Movie'),
        ),
    ]
